import {Range} from 'my-nft-gen/src/core/layer/configType/Range.js';
import {DynamicRange} from 'my-nft-gen/src/core/layer/configType/DynamicRange.js';
import {PercentageRange} from 'my-nft-gen/src/core/layer/configType/PercentageRange.js';
import {PercentageShortestSide} from 'my-nft-gen/src/core/layer/configType/PercentageShortestSide.js';

export const FRACTAL_DENDRITE_PRESETS = [
    {
        name: 'sparse-sapling',
        effect: 'fractal-dendrite',
        displayName: 'Sparse Sapling',
        description: 'Minimal branching with shallow depth for delicate tree silhouettes',
        percentChance: 100,
        currentEffectConfig: {
            maxDepth: new Range(4, 6),
            branchCount: new Range(2, 2),
            branchAngleSpread: new Range(15, 25),
            thickness: 1.5,
            accentRange: new DynamicRange(new Range(1, 1), new Range(3, 5)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'dense-canopy',
        effect: 'fractal-dendrite',
        displayName: 'Dense Canopy',
        description: 'Deep recursive branching with wide spread for lush canopy',
        percentChance: 100,
        currentEffectConfig: {
            maxDepth: new Range(8, 10),
            branchCount: new Range(3, 4),
            branchAngleSpread: new Range(35, 50),
            thickness: 3,
            trunkLength: new PercentageRange(new PercentageShortestSide(0.18), new PercentageShortestSide(0.3)),
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(3, 6),
        },
    },
    {
        name: 'frost-crystal',
        effect: 'fractal-dendrite',
        displayName: 'Frost Crystal',
        description: 'Fast rotating dendrite with tight angles resembling ice crystals',
        percentChance: 100,
        currentEffectConfig: {
            maxDepth: new Range(7, 9),
            branchCount: new Range(3, 3),
            branchAngleSpread: new Range(55, 65),
            speed: new Range(2, 3),
            growthOscillation: new Range(2, 4),
            accentRange: new DynamicRange(new Range(1, 2), new Range(4, 8)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const PLASMA_CURRENT_PRESETS = [
    {
        name: 'gentle-spark',
        effect: 'plasma-current',
        displayName: 'Gentle Spark',
        description: 'Few arcs with minimal forking for subtle electric accents',
        percentChance: 100,
        currentEffectConfig: {
            numberOfArcs: new Range(2, 4),
            forkDepth: new Range(1, 2),
            segmentsPerArc: new Range(6, 10),
            jaggedness: new Range(3, 8),
            accentRange: new DynamicRange(new Range(1, 2), new Range(4, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 5)),
            featherTimes: new Range(2, 5),
        },
    },
    {
        name: 'lightning-storm',
        effect: 'plasma-current',
        displayName: 'Lightning Storm',
        description: 'Many arcs with deep forking for intense plasma discharge',
        percentChance: 100,
        currentEffectConfig: {
            numberOfArcs: new Range(6, 10),
            forkDepth: new Range(4, 6),
            segmentsPerArc: new Range(12, 20),
            jaggedness: new Range(15, 30),
            thickness: 3,
            accentRange: new DynamicRange(new Range(3, 5), new Range(8, 14)),
            blurRange: new DynamicRange(new Range(3, 5), new Range(7, 12)),
            featherTimes: new Range(3, 8),
        },
    },
    {
        name: 'tesla-coil',
        effect: 'plasma-current',
        displayName: 'Tesla Coil',
        description: 'Rapid pulsing plasma with high wobble',
        percentChance: 100,
        currentEffectConfig: {
            numberOfArcs: new Range(4, 7),
            forkDepth: new Range(3, 5),
            pulseFrequency: new Range(4, 8),
            speed: new Range(2, 4),
            accentRange: new DynamicRange(new Range(2, 4), new Range(6, 12)),
            blurRange: new DynamicRange(new Range(2, 4), new Range(5, 10)),
            featherTimes: new Range(4, 10),
        },
    },
];

export const SACRED_MANDALA_PRESETS = [
    {
        name: 'simple-yantra',
        effect: 'sacred-mandala',
        displayName: 'Simple Yantra',
        description: 'Low symmetry mandala with few rings for clean geometric pattern',
        percentChance: 100,
        currentEffectConfig: {
            symmetryFold: new Range(4, 6),
            concentricRings: new Range(2, 4),
            petalLayers: new Range(1, 2),
            dotCount: new Range(4, 8),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'ornate-temple',
        effect: 'sacred-mandala',
        displayName: 'Ornate Temple',
        description: 'High symmetry with many concentric rings and dense dot arrays',
        percentChance: 100,
        currentEffectConfig: {
            symmetryFold: new Range(10, 16),
            concentricRings: new Range(6, 10),
            petalLayers: new Range(3, 5),
            dotCount: new Range(12, 24),
            dotRadius: new Range(3, 8),
            thickness: 2.5,
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(3, 7),
        },
    },
    {
        name: 'breathing-lotus',
        effect: 'sacred-mandala',
        displayName: 'Breathing Lotus',
        description: 'Deep breathing animation with petal emphasis',
        percentChance: 100,
        currentEffectConfig: {
            symmetryFold: new Range(6, 10),
            petalLayers: new Range(3, 5),
            breathFrequency: new Range(2, 4),
            breathAmplitude: 0.14,
            speed: new Range(1, 2),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const VORONOI_SHATTER_PRESETS = [
    {
        name: 'cracked-glass',
        effect: 'voronoi-shatter',
        displayName: 'Cracked Glass',
        description: 'Few large cells for a shattered glass aesthetic',
        percentChance: 100,
        currentEffectConfig: {
            numberOfSeeds: new Range(6, 12),
            thickness: 3,
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(2, 5),
        },
    },
    {
        name: 'cellular-tissue',
        effect: 'voronoi-shatter',
        displayName: 'Cellular Tissue',
        description: 'Dense small cells mimicking biological tissue',
        percentChance: 100,
        currentEffectConfig: {
            numberOfSeeds: new Range(30, 50),
            thickness: 1,
            driftAmplitude: new Range(2, 8),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 3)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'drifting-plates',
        effect: 'voronoi-shatter',
        displayName: 'Drifting Plates',
        description: 'Medium cells with strong seed drift animation',
        percentChance: 100,
        currentEffectConfig: {
            numberOfSeeds: new Range(16, 24),
            driftAmplitude: new Range(15, 30),
            speed: new Range(2, 3),
            accentRange: new DynamicRange(new Range(1, 2), new Range(4, 8)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const MOIRE_INTERFERENCE_PRESETS = [
    {
        name: 'subtle-weave',
        effect: 'moire-interference',
        displayName: 'Subtle Weave',
        description: 'Few grids with wide spacing for gentle interference patterns',
        percentChance: 100,
        currentEffectConfig: {
            numberOfGrids: new Range(2, 2),
            lineSpacing: new Range(16, 24),
            rotationRange: new Range(20, 40),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(1, 3)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'optical-illusion',
        effect: 'moire-interference',
        displayName: 'Optical Illusion',
        description: 'Dense grids with tight spacing for intense moiré effect',
        percentChance: 100,
        currentEffectConfig: {
            numberOfGrids: new Range(3, 5),
            lineSpacing: new Range(5, 10),
            rotationRange: new Range(45, 90),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'ripple-mesh',
        effect: 'moire-interference',
        displayName: 'Ripple Mesh',
        description: 'Concentric rings combined with line grids',
        percentChance: 100,
        currentEffectConfig: {
            numberOfGrids: new Range(2, 3),
            concentricMode: true,
            concentricRingCount: new Range(20, 45),
            lineSpacing: new Range(10, 16),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const REACTION_DIFFUSION_PRESETS = [
    {
        name: 'gentle-spots',
        effect: 'reaction-diffusion',
        displayName: 'Gentle Spots',
        description: 'Low seed count producing sparse Turing spot patterns',
        percentChance: 100,
        currentEffectConfig: {
            seedCount: new Range(3, 6),
            contourLevels: new Range(3, 5),
            gridResolution: new Range(18, 25),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'labyrinth',
        effect: 'reaction-diffusion',
        displayName: 'Labyrinth',
        description: 'High contour density creating maze-like stripe topology',
        percentChance: 100,
        currentEffectConfig: {
            seedCount: new Range(10, 18),
            contourLevels: new Range(8, 12),
            gridResolution: new Range(35, 50),
            waveFrequency: new Range(4, 8),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'coral-reef',
        effect: 'reaction-diffusion',
        displayName: 'Coral Reef',
        description: 'Multiple modes with phase morphing for organic coral shapes',
        percentChance: 100,
        currentEffectConfig: {
            seedCount: new Range(8, 14),
            contourLevels: new Range(5, 8),
            noiseScale: new Range(5, 10),
            speed: new Range(1, 2),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const TOROIDAL_FLOW_PRESETS = [
    {
        name: 'gentle-ring',
        effect: 'toroidal-flow',
        displayName: 'Gentle Ring',
        description: 'Few streamlines with subtle donut topology',
        percentChance: 100,
        currentEffectConfig: {
            streamlineCount: new Range(8, 14),
            pointsPerStream: new Range(20, 35),
            spiralTightness: new Range(1, 3),
            wobbleAmplitude: new Range(1, 3),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'vortex-core',
        effect: 'toroidal-flow',
        displayName: 'Vortex Core',
        description: 'Dense streamlines with tight spiral for powerful vortex',
        percentChance: 100,
        currentEffectConfig: {
            streamlineCount: new Range(28, 40),
            pointsPerStream: new Range(50, 80),
            spiralTightness: new Range(5, 8),
            speed: new Range(2, 4),
            thickness: 2,
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(3, 7),
        },
    },
    {
        name: 'magnetic-field',
        effect: 'toroidal-flow',
        displayName: 'Magnetic Field',
        description: 'Wide aspect ratio torus resembling magnetic field lines',
        percentChance: 100,
        currentEffectConfig: {
            streamlineCount: new Range(16, 26),
            outerRadius: new PercentageRange(new PercentageShortestSide(0.3), new PercentageShortestSide(0.5)),
            innerRadius: new PercentageRange(new PercentageShortestSide(0.04), new PercentageShortestSide(0.08)),
            wobbleAmplitude: new Range(4, 10),
            wobbleFrequency: new Range(5, 10),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const GLYPH_MATRIX_PRESETS = [
    {
        name: 'whisper-rain',
        effect: 'glyph-matrix',
        displayName: 'Whisper Rain',
        description: 'Few columns with slow cascade for subtle digital rain',
        percentChance: 100,
        currentEffectConfig: {
            columnCount: new Range(5, 10),
            cascadeSpeed: new Range(1, 1),
            trailLength: new Range(3, 5),
            glyphSegments: new Range(2, 4),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'data-storm',
        effect: 'glyph-matrix',
        displayName: 'Data Storm',
        description: 'Many columns with fast cascade and long trails',
        percentChance: 100,
        currentEffectConfig: {
            columnCount: new Range(18, 30),
            cascadeSpeed: new Range(3, 5),
            trailLength: new Range(8, 14),
            glyphSize: new Range(8, 14),
            accentRange: new DynamicRange(new Range(2, 3), new Range(4, 8)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(3, 7),
        },
    },
    {
        name: 'cipher-wall',
        effect: 'glyph-matrix',
        displayName: 'Cipher Wall',
        description: 'Dense glyphs with complex segments filling the field',
        percentChance: 100,
        currentEffectConfig: {
            columnCount: new Range(14, 22),
            glyphSegments: new Range(5, 8),
            glyphSize: new Range(12, 22),
            trailLength: new Range(6, 10),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const PENROSE_TILING_PRESETS = [
    {
        name: 'sparse-quasicrystal',
        effect: 'penrose-tiling',
        displayName: 'Sparse Quasicrystal',
        description: 'Low subdivision for large visible kite and dart tiles',
        percentChance: 100,
        currentEffectConfig: {
            subdivisions: new Range(2, 3),
            thickness: 2,
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 5)),
            featherTimes: new Range(2, 5),
        },
    },
    {
        name: 'infinite-pattern',
        effect: 'penrose-tiling',
        displayName: 'Infinite Pattern',
        description: 'High subdivision revealing deep aperiodic structure',
        percentChance: 100,
        currentEffectConfig: {
            subdivisions: new Range(5, 7),
            thickness: 1,
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'pulsing-mosaic',
        effect: 'penrose-tiling',
        displayName: 'Pulsing Mosaic',
        description: 'Medium tiling with strong pulse animation',
        percentChance: 100,
        currentEffectConfig: {
            subdivisions: new Range(3, 5),
            pulseFrequency: new Range(3, 5),
            rotationSpeed: new Range(2, 3),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const GRAVITY_WELL_PRESETS = [
    {
        name: 'single-star',
        effect: 'gravity-well',
        displayName: 'Single Star',
        description: 'One gravity well with gentle grid distortion',
        percentChance: 100,
        currentEffectConfig: {
            wellCount: new Range(1, 1),
            wellStrength: new Range(20, 40),
            gridLines: new Range(16, 24),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 5)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'binary-system',
        effect: 'gravity-well',
        displayName: 'Binary System',
        description: 'Two orbiting wells creating complex spacetime curvature',
        percentChance: 100,
        currentEffectConfig: {
            wellCount: new Range(2, 2),
            wellStrength: new Range(50, 80),
            wellOrbitRadius: new Range(40, 80),
            speed: new Range(1, 2),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'galactic-cluster',
        effect: 'gravity-well',
        displayName: 'Galactic Cluster',
        description: 'Multiple wells with strong distortion for chaotic curvature',
        percentChance: 100,
        currentEffectConfig: {
            wellCount: new Range(3, 5),
            wellStrength: new Range(60, 100),
            gridLines: new Range(20, 30),
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(3, 7),
        },
    },
];

export const STAINED_GLASS_PRESETS = [
    {
        name: 'cathedral-window',
        effect: 'stained-glass',
        displayName: 'Cathedral Window',
        description: 'Large irregular polygons with thick leading for classic stained glass',
        percentChance: 100,
        currentEffectConfig: {
            cellCount: new Range(8, 15),
            leadingThickness: new Range(5, 8),
            thickness: 4,
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(2, 5),
        },
    },
    {
        name: 'mosaic-tile',
        effect: 'stained-glass',
        displayName: 'Mosaic Tile',
        description: 'Many small cells for fine mosaic texture',
        percentChance: 100,
        currentEffectConfig: {
            cellCount: new Range(35, 60),
            leadingThickness: new Range(2, 3),
            thickness: 2,
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'shimmering-chapel',
        effect: 'stained-glass',
        displayName: 'Shimmering Chapel',
        description: 'Medium cells with strong shimmer animation',
        percentChance: 100,
        currentEffectConfig: {
            cellCount: new Range(18, 30),
            shimmerFrequency: new Range(3, 6),
            accentRange: new DynamicRange(new Range(1, 3), new Range(4, 8)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const NEURAL_MESH_PRESETS = [
    {
        name: 'sparse-network',
        effect: 'neural-mesh',
        displayName: 'Sparse Network',
        description: 'Few neurons with long-range connections for minimal neural graph',
        percentChance: 100,
        currentEffectConfig: {
            neuronCount: new Range(10, 18),
            connectionMaxDist: new Range(120, 200),
            maxConnections: new Range(2, 3),
            neuronRadius: new Range(4, 8),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 5)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'deep-cortex',
        effect: 'neural-mesh',
        displayName: 'Deep Cortex',
        description: 'Dense neurons with many synaptic connections',
        percentChance: 100,
        currentEffectConfig: {
            neuronCount: new Range(50, 80),
            connectionMaxDist: new Range(50, 90),
            maxConnections: new Range(5, 8),
            neuronRadius: new Range(2, 5),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'firing-cascade',
        effect: 'neural-mesh',
        displayName: 'Firing Cascade',
        description: 'Fast pulsing neurons with visible signal propagation',
        percentChance: 100,
        currentEffectConfig: {
            neuronCount: new Range(30, 50),
            pulseFrequency: new Range(4, 8),
            speed: new Range(2, 3),
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(3, 8),
        },
    },
];

export const CHLADNI_PLATE_PRESETS = [
    {
        name: 'low-frequency',
        effect: 'chladni-plate',
        displayName: 'Low Frequency',
        description: 'Simple eigenmode with wide nodal line spacing',
        percentChance: 100,
        currentEffectConfig: {
            modeM: new Range(1, 2),
            modeN: new Range(1, 2),
            resolution: new Range(25, 35),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'harmonic-overtone',
        effect: 'chladni-plate',
        displayName: 'Harmonic Overtone',
        description: 'Multiple modes superimposed for complex nodal geometry',
        percentChance: 100,
        currentEffectConfig: {
            modeM: new Range(4, 7),
            modeN: new Range(4, 7),
            resolution: new Range(50, 70),
            nodalThreshold: new Range(2, 4),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'morphing-resonance',
        effect: 'chladni-plate',
        displayName: 'Morphing Resonance',
        description: 'Animated mode morphing showing shifting vibration patterns',
        percentChance: 100,
        currentEffectConfig: {
            morphSpeed: new Range(2, 4),
            modeM: new Range(2, 5),
            modeN: new Range(2, 5),
            speed: new Range(1, 2),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const PHYLLOTAXIS_SPIRAL_PRESETS = [
    {
        name: 'sunflower-seed',
        effect: 'phyllotaxis-spiral',
        displayName: 'Sunflower Seed',
        description: 'Classic golden angle spiral with uniform sizing',
        percentChance: 100,
        currentEffectConfig: {
            dotCount: new Range(80, 150),
            dotMinRadius: new Range(2, 3),
            dotMaxRadius: new Range(3, 5),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'fibonacci-bloom',
        effect: 'phyllotaxis-spiral',
        displayName: 'Fibonacci Bloom',
        description: 'Many points with strong size gradient for blooming flower',
        percentChance: 100,
        currentEffectConfig: {
            dotCount: new Range(250, 400),
            dotMinRadius: new Range(1, 2),
            dotMaxRadius: new Range(8, 14),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'breathing-galaxy',
        effect: 'phyllotaxis-spiral',
        displayName: 'Breathing Galaxy',
        description: 'Deep breathing animation with rotation for galaxy-like spiral',
        percentChance: 100,
        currentEffectConfig: {
            dotCount: new Range(180, 300),
            breathFrequency: new Range(2, 4),
            breathAmplitude: 0.12,
            speed: new Range(1, 2),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const TOPOGRAPHIC_CONTOUR_PRESETS = [
    {
        name: 'gentle-hills',
        effect: 'topographic-contour',
        displayName: 'Gentle Hills',
        description: 'Few wide peaks with sparse contour lines',
        percentChance: 100,
        currentEffectConfig: {
            peakCount: new Range(1, 2),
            contourLevels: new Range(5, 8),
            resolution: new Range(25, 35),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'mountain-range',
        effect: 'topographic-contour',
        displayName: 'Mountain Range',
        description: 'Multiple sharp peaks with dense contour intervals',
        percentChance: 100,
        currentEffectConfig: {
            peakCount: new Range(4, 7),
            contourLevels: new Range(14, 22),
            resolution: new Range(40, 60),
            thickness: 2,
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'drifting-landscape',
        effect: 'topographic-contour',
        displayName: 'Drifting Landscape',
        description: 'Animated peak drift creating shifting terrain',
        percentChance: 100,
        currentEffectConfig: {
            peakCount: new Range(3, 5),
            sweepSpeed: new Range(2, 4),
            speed: new Range(1, 2),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const RADIOLARIA_SKELETON_PRESETS = [
    {
        name: 'simple-diatom',
        effect: 'radiolaria-skeleton',
        displayName: 'Simple Diatom',
        description: 'Few shells with sparse spines for clean microscopic organism',
        percentChance: 100,
        currentEffectConfig: {
            shellCount: new Range(2, 3),
            spineCount: new Range(6, 10),
            spineLength: new Range(15, 30),
            latticeSegments: new Range(3, 5),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'ornate-radiolarian',
        effect: 'radiolaria-skeleton',
        displayName: 'Ornate Radiolarian',
        description: 'Many nested shells with dense barbed spines',
        percentChance: 100,
        currentEffectConfig: {
            shellCount: new Range(5, 7),
            spineCount: new Range(16, 24),
            spineLength: new Range(40, 70),
            latticeSegments: new Range(6, 10),
            symmetryFold: new Range(8, 12),
            thickness: 2,
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(3, 7),
        },
    },
    {
        name: 'pulsing-protozoa',
        effect: 'radiolaria-skeleton',
        displayName: 'Pulsing Protozoa',
        description: 'Breathing animation with medium complexity for organic feel',
        percentChance: 100,
        currentEffectConfig: {
            shellCount: new Range(3, 5),
            breathFrequency: new Range(2, 4),
            speed: new Range(1, 2),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const CELTIC_KNOTWORK_PRESETS = [
    {
        name: 'simple-trefoil',
        effect: 'celtic-knotwork',
        displayName: 'Simple Trefoil',
        description: 'Three-lobed knot with single band for classic Celtic motif',
        percentChance: 100,
        currentEffectConfig: {
            lobeCount: new Range(3, 3),
            bandCount: new Range(1, 2),
            thickness: 4,
            lobeDepth: new Range(30, 50),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 5)),
            featherTimes: new Range(2, 5),
        },
    },
    {
        name: 'complex-weave',
        effect: 'celtic-knotwork',
        displayName: 'Complex Weave',
        description: 'Many lobes with multiple parallel bands for dense interlace',
        percentChance: 100,
        currentEffectConfig: {
            lobeCount: new Range(6, 8),
            bandCount: new Range(3, 5),
            weaveGap: new Range(6, 10),
            thickness: 2,
            accentRange: new DynamicRange(new Range(1, 2), new Range(4, 8)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'eternal-knot',
        effect: 'celtic-knotwork',
        displayName: 'Eternal Knot',
        description: 'Medium complexity with pulsing animation and deep lobes',
        percentChance: 100,
        currentEffectConfig: {
            lobeCount: new Range(4, 6),
            lobeDepth: new Range(50, 90),
            pulseFrequency: new Range(2, 3),
            speed: new Range(1, 2),
            accentRange: new DynamicRange(new Range(1, 2), new Range(4, 8)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const LISSAJOUS_CAGE_PRESETS = [
    {
        name: 'simple-figure-eight',
        effect: 'lissajous-cage',
        displayName: 'Simple Figure-Eight',
        description: 'Low frequency ratios producing clean Lissajous figures',
        percentChance: 100,
        currentEffectConfig: {
            curveCount: new Range(1, 2),
            freqA: new Range(1, 2),
            freqB: new Range(1, 3),
            freqC: new Range(1, 2),
            resolution: new Range(200, 400),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'harmonic-cage',
        effect: 'lissajous-cage',
        displayName: 'Harmonic Cage',
        description: 'Multiple curves with high frequency ratios forming a wireframe cage',
        percentChance: 100,
        currentEffectConfig: {
            curveCount: new Range(4, 5),
            freqA: new Range(3, 5),
            freqB: new Range(3, 5),
            freqC: new Range(2, 4),
            depthScale: new Range(50, 80),
            resolution: new Range(400, 700),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'tumbling-orbit',
        effect: 'lissajous-cage',
        displayName: 'Tumbling Orbit',
        description: 'Fast tumbling rotation with deep perspective projection',
        percentChance: 100,
        currentEffectConfig: {
            speed: new Range(2, 3),
            tumbleFrequency: new Range(2, 3),
            depthScale: new Range(60, 90),
            curveCount: new Range(2, 4),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const WAVE_COLLAPSE_PRESETS = [
    {
        name: 'small-grid',
        effect: 'wave-collapse',
        displayName: 'Small Grid',
        description: 'Few large cells with clear tile pattern visibility',
        percentChance: 100,
        currentEffectConfig: {
            cellCount: new Range(4, 6),
            tilePatterns: new Range(3, 4),
            gridSize: new PercentageRange(new PercentageShortestSide(0.3), new PercentageShortestSide(0.5)),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 5)),
            featherTimes: new Range(2, 5),
        },
    },
    {
        name: 'dense-lattice',
        effect: 'wave-collapse',
        displayName: 'Dense Lattice',
        description: 'Many small cells with diverse tile patterns',
        percentChance: 100,
        currentEffectConfig: {
            cellCount: new Range(12, 16),
            tilePatterns: new Range(5, 8),
            gridSize: new PercentageRange(new PercentageShortestSide(0.4), new PercentageShortestSide(0.7)),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'cascading-resolve',
        effect: 'wave-collapse',
        displayName: 'Cascading Resolve',
        description: 'Fast collapse wave sweeping through the grid',
        percentChance: 100,
        currentEffectConfig: {
            cellCount: new Range(8, 12),
            collapseSpeed: new Range(2, 4),
            waveFrequency: new Range(2, 3),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
];

export const SONIC_ROSETTE_PRESETS = [
    {
        name: 'simple-petals',
        effect: 'sonic-rosette',
        displayName: 'Simple Petals',
        description: 'Low petal count rose curve for clean floral pattern',
        percentChance: 100,
        currentEffectConfig: {
            petalNumerator: new Range(3, 4),
            petalDenominator: new Range(1, 1),
            layerCount: new Range(1, 2),
            harmonicDepth: new Range(0, 1),
            resolution: new Range(300, 500),
            accentRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            blurRange: new DynamicRange(new Range(1, 1), new Range(2, 4)),
            featherTimes: new Range(2, 4),
        },
    },
    {
        name: 'complex-rhodonea',
        effect: 'sonic-rosette',
        displayName: 'Complex Rhodonea',
        description: 'High frequency ratio producing many overlapping petals',
        percentChance: 100,
        currentEffectConfig: {
            petalNumerator: new Range(7, 9),
            petalDenominator: new Range(3, 5),
            layerCount: new Range(3, 5),
            harmonicDepth: new Range(2, 3),
            resolution: new Range(600, 900),
            accentRange: new DynamicRange(new Range(1, 2), new Range(3, 7)),
            blurRange: new DynamicRange(new Range(1, 2), new Range(3, 6)),
            featherTimes: new Range(2, 6),
        },
    },
    {
        name: 'modulated-bloom',
        effect: 'sonic-rosette',
        displayName: 'Modulated Bloom',
        description: 'Strong harmonic overtones creating petal-edge modulation',
        percentChance: 100,
        currentEffectConfig: {
            petalNumerator: new Range(4, 7),
            petalDenominator: new Range(1, 3),
            harmonicDepth: new Range(2, 3),
            harmonicAmplitude: new Range(15, 30),
            breathFrequency: new Range(2, 3),
            accentRange: new DynamicRange(new Range(2, 3), new Range(5, 9)),
            blurRange: new DynamicRange(new Range(2, 3), new Range(4, 7)),
            featherTimes: new Range(3, 7),
        },
    },
];

export const ALL_PRESETS = {
    'fractal-dendrite': FRACTAL_DENDRITE_PRESETS,
    'plasma-current': PLASMA_CURRENT_PRESETS,
    'sacred-mandala': SACRED_MANDALA_PRESETS,
    'voronoi-shatter': VORONOI_SHATTER_PRESETS,
    'moire-interference': MOIRE_INTERFERENCE_PRESETS,
    'reaction-diffusion': REACTION_DIFFUSION_PRESETS,
    'toroidal-flow': TOROIDAL_FLOW_PRESETS,
    'glyph-matrix': GLYPH_MATRIX_PRESETS,
    'penrose-tiling': PENROSE_TILING_PRESETS,
    'gravity-well': GRAVITY_WELL_PRESETS,
    'stained-glass': STAINED_GLASS_PRESETS,
    'neural-mesh': NEURAL_MESH_PRESETS,
    'chladni-plate': CHLADNI_PLATE_PRESETS,
    'phyllotaxis-spiral': PHYLLOTAXIS_SPIRAL_PRESETS,
    'topographic-contour': TOPOGRAPHIC_CONTOUR_PRESETS,
    'radiolaria-skeleton': RADIOLARIA_SKELETON_PRESETS,
    'celtic-knotwork': CELTIC_KNOTWORK_PRESETS,
    'lissajous-cage': LISSAJOUS_CAGE_PRESETS,
    'wave-collapse': WAVE_COLLAPSE_PRESETS,
    'sonic-rosette': SONIC_ROSETTE_PRESETS,
};
